export const CREATURES = [
  {
    name: 'Gold Dragon',
    action_points_ground: 38,
    action_points_flying: 40,
    stamina: 86,
    constitution: 90,
    combat: 50,
    defence: 42,
    magic_resistance: 82,
    carry_limit: 30,
    potion_consumption: 10,
    victory_points: 9,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: yes,
    wood_type: no,
    water_type: yes,
    rock_type: no,
  },
  {
    name: 'Green Dragon',
    action_points_ground: 32,
    action_points_flying: 36,
    stamina: 80,
    constitution: 82,
    combat: 40,
    defence: 43,
    magic_resistance: 75,
    carry_limit: 26,
    potion_consumption: 10,
    victory_points: 8,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: yes,
    wood_type: yes,
    water_type: no,
    rock_type: no,
  },
  {
    name: 'Red Dragon',
    action_points_ground: 34,
    action_points_flying: 40,
    stamina: 90,
    constitution: 72,
    combat: 32,
    defence: 34,
    magic_resistance: 90,
    carry_limit: 32,
    potion_consumption: 10,
    victory_points: 7,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: yes,
    wood_type: no,
    water_type: no,
    rock_type: yes,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
]
