export const CREATURES = [
  {
    name: 'Gold Dragon',
    action_points_ground: 38,
    action_points_flying: 40,
    stamina: 86,
    constitution: 90,
    combat: 50,
    defence: 42,
    magic_resistance: 82,
    carry_limit: 30,
    potion_consumption: 10,
    victory_points: 9,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: true,
    wood_type: false,
    water_type: true,
    rock_type: false,
  },
  {
    name: 'Green Dragon',
    action_points_ground: 32,
    action_points_flying: 36,
    stamina: 80,
    constitution: 82,
    combat: 40,
    defence: 43,
    magic_resistance: 75,
    carry_limit: 26,
    potion_consumption: 10,
    victory_points: 8,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: true,
    wood_type: true,
    water_type: false,
    rock_type: false,
  },
  {
    name: 'Red Dragon',
    action_points_ground: 34,
    action_points_flying: 40,
    stamina: 90,
    constitution: 72,
    combat: 32,
    defence: 34,
    magic_resistance: 90,
    carry_limit: 32,
    potion_consumption: 10,
    victory_points: 7,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: true,
    wood_type: false,
    water_type: false,
    rock_type: true,
  },
  {
    name: 'Pixie',
    action_points_ground: 34,
    action_points_flying: 0,
    stamina: 40,
    constitution: 16,
    combat: 4,
    defence: 6,
    magic_resistance: 67,
    carry_limit: 30,
    potion_consumption: 2,
    victory_points: 1,
    mount: false,
    ride_mounts: true,
    undead: false,
    use_weapons: true,
    use_options: true,
    wood_type: true,
    water_type: false,
    rock_type: false,
  },
  {
    name: 'Dwarf',
    action_points_ground: 26,
    action_points_flying: 0,
    stamina: 57,
    constitution: 25,
    combat: 6,
    defence: 6,
    magic_resistance: 40,
    carry_limit: 35,
    potion_consumption: 2,
    victory_points: 1,
    mount: false,
    ride_mounts: true,
    undead: false,
    use_weapons: true,
    use_options: true,
    wood_type: false,
    water_type: false,
    rock_type: true,
  },
  {
    name: 'Goblin',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 45,
    constitution: 32,
    combat: 9,
    defence: 9,
    magic_resistance: 46,
    carry_limit: 42,
    potion_consumption: 2,
    victory_points: 1,
    mount: false,
    ride_mounts: true,
    undead: false,
    use_weapons: true,
    use_options: true,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: 'Troll',
    action_points_ground: 32,
    action_points_flying: 0,
    stamina: 88,
    constitution: 47,
    combat: 12,
    defence: 16,
    magic_resistance: 46,
    carry_limit: 40,
    potion_consumption: 2,
    victory_points: 2,
    mount: false,
    ride_mounts: true,
    undead: false,
    use_weapons: true,
    use_options: true,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: 'Giant',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 48,
    constitution: 66,
    combat: 21,
    defence: 15,
    magic_resistance: 50,
    carry_limit: 50,
    potion_consumption: 4,
    victory_points: 3,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: true,
    use_options: true,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: 'Centaur',
    action_points_ground: 48,
    action_points_flying: 0,
    stamina: 62,
    constitution: 36,
    combat: 8,
    defence: 10,
    magic_resistance: 54,
    carry_limit: 34,
    potion_consumption: 3,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: true,
    use_options: true,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: 'Unicorn',
    action_points_ground: 56,
    action_points_flying: 0,
    stamina: 72,
    constitution: 40,
    combat: 12,
    defence: 9,
    magic_resistance: 42,
    carry_limit: 0,
    potion_consumption: 3,
    victory_points: 1,
    mount: true,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: true,
  },
  {
    name: 'Pegasus',
    action_points_ground: 46,
    action_points_flying: 56,
    stamina: 80,
    constitution: 40,
    combat: 8,
    defence: 9,
    magic_resistance: 50,
    carry_limit: 0,
    potion_consumption: 3,
    victory_points: 1,
    mount: true,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: 'Grypthon',
    action_points_ground: 42,
    action_points_flying: 52,
    stamina: 73,
    constitution: 53,
    combat: 24,
    defence: 21,
    magic_resistance: 57,
    carry_limit: 0,
    potion_consumption: 4,
    victory_points: 4,
    mount: true,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: true,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: false,
    ride_mounts: false,
    undead: false,
    use_weapons: false,
    use_options: false,
    wood_type: false,
    water_type: false,
    rock_type: false,
  },
]

export const WEAPONS = [
  {
    name: 'sword',
    weight: 10,
    combat: 10,
    defence: 4,
    thrown_combat: 16,
    ranged_combat: 0,
  },
  {
    name: 'magic sword',
    weight: 10,
    combat: 20,
    defence: 8,
    thrown_combat: 32,
    ranged_combat: 0,
  },
  {
    name: 'knife',
    weight: 3,
    combat: 4,
    defence: 1,
    thrown_combat: 20,
    ranged_combat: 0,
  },
  {
    name: 'magic knife',
    weight: 3,
    combat: 8,
    defence: 2,
    thrown_combat: 40,
    ranged_combat: 0,
  },
  {
    name: 'shield',
    weight: 8,
    combat: 0,
    defence: 13,
    thrown_combat: 0,
    ranged_combat: 0,
  },
  {
    name: 'magic shield',
    weight: 8,
    combat: 0,
    defence: 26,
    thrown_combat: 0,
    ranged_combat: 0,
  },
  {
    name: 'bow',
    weight: 4,
    combat: 0,
    defence: 0,
    thrown_combat: 0,
    ranged_combat: 15,
  },
  {
    name: 'magic bow',
    weight: 4,
    combat: 0,
    defence: 0,
    thrown_combat: 0,
    ranged_combat: 30,
  },
  {
    name: 'spear',
    weight: 5,
    combat: 8,
    defence: 4,
    thrown_combat: 23,
    ranged_combat: 0,
  },
  {
    name: 'magic spear',
    weight: 5,
    combat: 16,
    defence: 8,
    thrown_combat: 46,
    ranged_combat: 0,
  },
  {
    name: 'club',
    weight: 9,
    combat: 5,
    defence: 1,
    thrown_combat: 8,
    ranged_combat: 0,
  },
  {
    name: 'magic club',
    weight: 9,
    combat: 10,
    defence: 2,
    thrown_combat: 16,
    ranged_combat: 0,
  },
  {
    name: 'axe',
    weight: 7,
    combat: 9,
    defence: 0,
    thrown_combat: 28,
    ranged_combat: 0,
  },
  {
    name: 'magic axe',
    weight: 7,
    combat: 18,
    defence: 0,
    thrown_combat: 56,
    ranged_combat: 0,
  },
  {
    name: 'ninja star',
    weight: 4,
    combat: 0,
    defence: 0,
    thrown_combat: 25,
    ranged_combat: 0,
  },
  {
    name: 'magic ninja star',
    weight: 4,
    combat: 0,
    defence: 0,
    thrown_combat: 50,
    ranged_combat: 0,
  },
  {
    name: 'slayer',
    weight: 9,
    combat: 12,
    defence: 4,
    thrown_combat: 8,
    ranged_combat: 0,
  },
  {
    name: 'magic slayer',
    weight: 9,
    combat: 30,
    defence: 12,
    thrown_combat: 16,
    ranged_combat: 0,
  }, 
]