export const CREATURES = [
  {
    name: 'Gold Dragon',
    action_points_ground: 38,
    action_points_flying: 40,
    stamina: 86,
    constitution: 90,
    combat: 50,
    defence: 42,
    magic_resistance: 82,
    carry_limit: 30,
    potion_consumption: 10,
    victory_points: 9,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: yes,
    wood_type: no,
    water_type: yes,
    rock_type: no,
  },
  {
    name: 'Green Dragon',
    action_points_ground: 32,
    action_points_flying: 36,
    stamina: 80,
    constitution: 82,
    combat: 40,
    defence: 43,
    magic_resistance: 75,
    carry_limit: 26,
    potion_consumption: 10,
    victory_points: 8,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: yes,
    wood_type: yes,
    water_type: no,
    rock_type: no,
  },
  {
    name: 'Red Dragon',
    action_points_ground: 34,
    action_points_flying: 40,
    stamina: 90,
    constitution: 72,
    combat: 32,
    defence: 34,
    magic_resistance: 90,
    carry_limit: 32,
    potion_consumption: 10,
    victory_points: 7,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: yes,
    wood_type: no,
    water_type: no,
    rock_type: yes,
  },
  {
    name: '',
    action_points_ground: 336,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
  {
    name: '',
    action_points_ground: 30,
    action_points_flying: 0,
    stamina: 70,
    constitution: 40,
    combat: 10,
    defence: 10,
    magic_resistance: 50,
    carry_limit: 30,
    potion_consumption: 4,
    victory_points: 1,
    mount: no,
    ride_mounts: no,
    undead: no,
    use_weapons: no,
    use_options: no,
    wood_type: no,
    water_type: no,
    rock_type: no,
  },
]

export const WEAPONS = [
  {
    name: 'sword',
    weight: 10,
    combat: 10,
    defence: 4,
    thrown_combat: 16,
    ranged_combat: 0,
  },
  {
    name: 'magic sword',
    weight: 10,
    combat: 20,
    defence: 8,
    thrown_combat: 32,
    ranged_combat: 0,
  },
  {
    name: 'knife',
    weight: 3,
    combat: 4,
    defence: 1,
    thrown_combat: 20,
    ranged_combat: 0,
  },
  {
    name: 'magic knife',
    weight: 3,
    combat: 8,
    defence: 2,
    thrown_combat: 40,
    ranged_combat: 0,
  },
  {
    name: 'shield',
    weight: 8,
    combat: 0,
    defence: 13,
    thrown_combat: 0,
    ranged_combat: 0,
  },
  {
    name: 'magic shield',
    weight: 8,
    combat: 0,
    defence: 26,
    thrown_combat: 0,
    ranged_combat: 0,
  },
  {
    name: 'bow',
    weight: 4,
    combat: 0,
    defence: 0,
    thrown_combat: 0,
    ranged_combat: 15,
  },
  {
    name: 'magic bow',
    weight: 4,
    combat: 0,
    defence: 0,
    thrown_combat: 0,
    ranged_combat: 30,
  },
  {
    name: 'spear',
    weight: 5,
    combat: 8,
    defence: 4,
    thrown_combat: 23,
    ranged_combat: 0,
  },
  {
    name: 'magic spear',
    weight: 5,
    combat: 16,
    defence: 8,
    thrown_combat: 46,
    ranged_combat: 0,
  },
  {
    name: 'club',
    weight: 9,
    combat: 5,
    defence: 1,
    thrown_combat: 8,
    ranged_combat: 0,
  },
  {
    name: 'magic club',
    weight: 9,
    combat: 10,
    defence: 2,
    thrown_combat: 16,
    ranged_combat: 0,
  },
  {
    name: 'axe',
    weight: 7,
    combat: 9,
    defence: 0,
    thrown_combat: 28,
    ranged_combat: 0,
  },
  {
    name: 'magic axe',
    weight: 7,
    combat: 18,
    defence: 0,
    thrown_combat: 56,
    ranged_combat: 0,
  },
  {
    name: 'ninja star',
    weight: 4,
    combat: 0,
    defence: 0,
    thrown_combat: 25,
    ranged_combat: 0,
  },
  {
    name: 'magic ninja star',
    weight: 4,
    combat: 0,
    defence: 0,
    thrown_combat: 50,
    ranged_combat: 0,
  },
  {
    name: 'slayer',
    weight: 9,
    combat: 12,
    defence: 4,
    thrown_combat: 8,
    ranged_combat: 0,
  },
  {
    name: 'magic slayer',
    weight: 9,
    combat: 30,
    defence: 12,
    thrown_combat: 16,
    ranged_combat: 0,
  }, 
]