export const PLAYER = {
  name: 'Player',
  max_ap: 36,
  ap: 36,
  stamina: 70,
  constitution: 40,
  combat: 10,
  defence: 10,
  magic_resistance: 50,
  carry_limit: 30,
  potion_consumption: 4,
  victory_points: 1,
  mount: false,
  ride_mounts: false,
  undead: false,
  use_weapons: false,
  use_options: false,
  wood_type: false,
  water_type: false,
  rock_type: false,
}
